spring:
  application-name: paperize
  base-url: ${BASE_URL}

  # SMPT host, this is localhost for development, it should work with your mailpit docker container.
  # You can open mailpit ui on http://localhost:8025 to see all emails sent from your application in development
  # You will use the host from the provider of your choice in production
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    session:
      cookie:
        http-only: true
        secure: false
        same-site: None

  allowed-origins:
    - "http://localhost:5173"

  sign-in-success-url: "http://localhost:5173/"

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}

          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace

      springframework:
        web: DEBUG
        security: DEBUG

org:
  jobrunr:
    background-job-server:
      enabled: true
    dashboard:
      enabled: true

aws:
  region: ${AWS_BUCKET_REGION}
  client-id: ${AWS_S3_CLIENT_ID}
  secret-key: ${AWS_S3_SECRET_KEY}
  bucket-name: ${BUCKET_NAME}